### ISSUE TITLE
Type error when passing null as metadata

### ISSUE THREAD

**Issue by barlock** [IBM/alchemy-logging#132]
## Describe the bug

When calling `alog.debug('some message', null)` you get the TypeError

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at AlogCoreSingleton.log (project/node_modules/alchemy-logging/src/core.ts:477:70)
    at AlogCoreSingleton.debug (project/node_modules/alchemy-logging/src/core.ts:281:37)
    at ChannelLog.debug (project/node_modules/alchemy-logging/src/channel-log.ts:118:37)
```

## Platform

- [ ] `python`
  * Interpreter version:
  * Library version:
- [x] `typescript`
  * `node` version: 16
  * Package version: 1.3
- [ ] `go`
  * Operating system:
  * Compiler version:
  * Package version:
- [ ] `c++`
  * Operating system:
  * Compiler version:
  * Library version:
  * Project build system:

## Sample Code
Please include a minimal sample of the code that will (if possible) reproduce the bug in isolation

`alog.debug('some message', null)`

## Expected behavior

It should log without any metadata

## Observed behavior
What you see happening (error messages, stack traces, etc...)

Typeerror above

**Comment by gabe-l-hart** [comment]
Closed by #133
