### ISSUE TITLE
[c++] Add boost algorithm and locale deps via CPM

### ISSUE THREAD

**Issue by gabe-l-hart** [IBM/alchemy-logging#39]
## Description

As a developer using [CPM](https://github.com/cpm-cmake/CPM.cmake), I want to be able to include `alog` and get _all_ of its dependencies automatically populated, including the sub-libraries of `boost` needed at build time for `alog` so that I can treat the `alog` build as a black-box.

## Details

The [boost](https://github.com/boostorg/boost) project is HUGE! Just the download step can take a very long time, so we want to ensure that users of `alog` do not need to spend hours waiting for the dependencies to populate. At the same time, it is not a good user experience to require that boost be installed at the system level. This story is to figure out if it's possible to use CPM to download _just_ the `algorithm` and `locale` modules (and `regex` if unit tests are enabled).

## Acceptance Criteria

- [ ] A project which use CPM to include `alog` does not need `boost` pre-installed
- [ ] The `release_test` phase of the `c++` dockerfile starts from a base phase that does not include `boost` pre-installed
- [ ] The dependency phase of the `cmake` configuration doesn't take forever!

**Comment by jlquinn** [comment]
Hi Gabe, the simpler approach would be to drop the boost requirement.  Boost is used for string join and wstring to string conversion.  Join is easy to replace.  If we're guaranteed that the wstring input is Unicode (aka UTF-16 or UTF-32), then it's pretty easy to just write a converter and avoid the large external dependency.

**Comment by gabe-l-hart** [comment]
Good point @jlquinn! To be honest, when moving this to open source, it had been long enough since I wrote it that I was a bit rusty. I'll take a look at what it would take to do this, but it might be a few before I get to it. Is the `boost` dependency an issue for your usage? It _would_ be really nice to drop the dependency and make this lighter weight to adopt.

**Comment by jlquinn** [comment]
The main issue is that we are already using system boost, so it will make things messy to coordinate boost versions.  That and compile time is already pretty long (20m on many cores) and adding boost as a compile-time dependency will make that longer.

**Comment by gabe-l-hart** [comment]
This issue is closed by #114 since `boost` has been removed
